### ISSUE TITLE
Dependency hell

### ISSUE THREAD

**Issue by mjbeyeler** [conda-forge/pandas-feedstock#63]
Hello!

I built a pandas environment from my miniconda via

`conda create -n myenv pandas`

using `conda-forge` channel,

and the resulting environment isn't functional on my Linux x64 machine.

When I do the same using `defaults` channel, I get a functional pandas environment.

I don't have the time to look into it myself, and just wanted to let you know that your feedstock is broken atm.

Best

**Comment by TomAugspurger** [comment]
More details would be helpful, otherwise it seems more likely that it's something specific to your machine than the package itself.

**Comment by mjbeyeler** [comment]
Hmm, well I'm running the default miniconda installation, and my channel hierarchy, from highest to lowest priority, is:

```conda-forge
bioconda
defaults
```

This should be all information required to reproduce my error, as far as I can tell.

To reproduce the error, type `python` in the Terminal, and then `import pandas as pd`, which returns the error

`Illegal construction (core dumped)`

**Comment by TomAugspurger** [comment]
See https://raw.githubusercontent.com/conda/conda/master/.github/ISSUE_TEMPLATE/Bug_report.md for the types of things that conda typically asks for.

**Comment by mjbeyeler** [comment]
What do you mean?

It's not a conda issue as far as I can tell.

When I create the environment via `conda create -n myenv -c defaults myenv`, then importing pandas works just fine.

So, I think we're looking at a specific `conda-forge` issue. Did you try reproducing the error?

**Comment by ocefpaf** [comment]
You are also using 3 channels that are not 100% compatible with each other. See https://conda-forge.org/docs/user/tipsandtricks.html#how-to-fix-it

**Comment by TomAugspurger** [comment]
Yes, I created a new env with conda-forge's pandas and things are fine.

**Comment by ocefpaf** [comment]
> So, I think we're looking at a specific conda-forge issue. Did you try reproducing the error?

Nope. It is a mixing channel issue. Please check https://conda-forge.org/docs/user/tipsandtricks.html#using-multiple-channels

Closing this b/c it is not an actionable item on the pandas packages or conda-forge. conda-forge does not guarantee compatibility with third party channel and you should always use `strict` channel option for stability.

**Comment by mjbeyeler** [comment]
@ocefpaf I am  using the `strict` channel hierarchy option.

So, when I am installing using the commands described above, AND having `strict` channel option, I still have `libgcc-ng` and `libgfortran-ng` and `libstdcxx-ng` installed from `pkgs/main` when installing via `conda-forge`.

Also `conda-forge` doesn't install mkl-related packages nor `numpy-base`, chich `defaults` provides.

Do you have an idea what might be causing the problem then?

**Comment by ocefpaf** [comment]
The following `.condarc` is what you descrived, core=rect?

```yaml
channel_priority: strict
channels:
  - conda-forge
  - bioconda
  - defaults
```

and I just tested:

```shell
conda create --name TEST pandas --yes
conda activate TEST
python -c "import pandas; print(pandas.__version__)"      
0.24.2
```

and here is the `conda list`:

```
> conda list
# packages in environment at /home/filipe/miniconda3/envs/TEST:
#
# Name                    Version                   Build  Channel
bzip2                     1.0.6             h14c3975_1002    conda-forge
ca-certificates           2019.6.16            hecc5488_0    conda-forge
certifi                   2019.6.16                py37_0    conda-forge
libblas                   3.8.0                7_openblas    conda-forge
libcblas                  3.8.0                7_openblas    conda-forge
libffi                    3.2.1             he1b5a44_1006    conda-forge
libgcc-ng                 9.1.0                hdf63c60_0    defaults
libgfortran-ng            7.3.0                hdf63c60_0    defaults
liblapack                 3.8.0                7_openblas    conda-forge
libstdcxx-ng              9.1.0                hdf63c60_0    defaults
ncurses                   6.1               hf484d3e_1002    conda-forge
numpy                     1.16.4           py37h95a1406_0    conda-forge
openblas                  0.3.5             h9ac9557_1001    conda-forge
openssl                   1.1.1b               h14c3975_1    conda-forge
pandas                    0.24.2           py37hb3f55d8_0    conda-forge
pip                       19.1.1                   py37_0    conda-forge
python                    3.7.3                h5b0a415_0    conda-forge
python-dateutil           2.8.0                      py_0    conda-forge
pytz                      2019.1                     py_0    conda-forge
readline                  7.0               hf8c457e_1001    conda-forge
setuptools                41.0.1                   py37_0    conda-forge
six                       1.12.0                py37_1000    conda-forge
sqlite                    3.28.0               h8b20d00_0    conda-forge
tk                        8.6.9             hed695b0_1002    conda-forge
wheel                     0.33.4                   py37_0    conda-forge
xz                        5.2.4             h14c3975_1001    conda-forge
zlib                      1.2.11            h14c3975_1004    conda-forge
```

> Also conda-forge doesn't install mkl-related packages nor numpy-base, chich defaults provides. 

Yep. B/c they are incompatible with conda-forge's openblas numpy.

> Do you have an idea what might be causing the problem then?

If you are forcing `numpy-base` and/or `mkl`, that is the problem.

**Comment by mjbeyeler** [comment]
My `~/.condarc` is

```
channels:
  - conda-forge
  - bioconda
  - defaults
channel_priority: strict
```

I copy-pasted your exact code, and I get the same error as described above.

My `conda list`:

```
# packages in environment at /home/bioinf/miniconda3/envs/TEST:
#
# Name                    Version                   Build  Channel
bzip2                     1.0.6             h14c3975_1002    conda-forge
ca-certificates           2019.6.16            hecc5488_0    conda-forge
certifi                   2019.6.16                py37_0    conda-forge
libblas                   3.8.0                7_openblas    conda-forge
libcblas                  3.8.0                7_openblas    conda-forge
libffi                    3.2.1             he1b5a44_1006    conda-forge
libgcc-ng                 9.1.0                hdf63c60_0  
libgfortran-ng            7.3.0                hdf63c60_0  
liblapack                 3.8.0                7_openblas    conda-forge
libstdcxx-ng              9.1.0                hdf63c60_0  
ncurses                   6.1               hf484d3e_1002    conda-forge
numpy                     1.16.4           py37h95a1406_0    conda-forge
openblas                  0.3.5             h9ac9557_1001    conda-forge
openssl                   1.1.1b               h14c3975_1    conda-forge
pandas                    0.24.2           py37hb3f55d8_0    conda-forge
pip                       19.1.1                   py37_0    conda-forge
python                    3.7.3                h5b0a415_0    conda-forge
python-dateutil           2.8.0                      py_0    conda-forge
pytz                      2019.1                     py_0    conda-forge
readline                  7.0               hf8c457e_1001    conda-forge
setuptools                41.0.1                   py37_0    conda-forge
six                       1.12.0                py37_1000    conda-forge
sqlite                    3.28.0               h8b20d00_0    conda-forge
tk                        8.6.9             hed695b0_1002    conda-forge
wheel                     0.33.4                   py37_0    conda-forge
xz                        5.2.4             h14c3975_1001    conda-forge
zlib                      1.2.11            h14c3975_1004    conda-forge
```

They seem almost identical to me, except that the three non-`conda-forge` packages don't have the `defaults` tag for me. Very weird.

I'll get home soon and check with my home PC.

**Comment by ocefpaf** [comment]
> They seem almost identical to me, except that the three non-conda-forge packages don't have the defaults tag for me. Very weird.

Not weird, you can use `show_channel_urls: true` for that. Also, you did not mentioned if that worked or not or why you mentioned mkl and numpy-base. It is hard to help you with fragmented information. I'm assuming it is resolved and "filing this" as usage question.

**Comment by mjbeyeler** [comment]
Sorry if I haven't been clear, I have mentioned mkl and numpy-base because those packages are installed when building a pandas environment from the `defaults` channel.

Also, you were right that it's kind of has to be a machine-dependent issue. I ran your code snippet on my personal PC yesterday, and it worked. But it's still not working on my work PC.

using `show_channel_urls: true`, I get the following `conda list`, which, according to Word comparison tool is identical to your list... yet my environment's not working. Now that's weird no?

```
# packages in environment at /home/bioinf/miniconda3/envs/TEST:
#
# Name                    Version                   Build  Channel
bzip2                     1.0.6             h14c3975_1002    conda-forge
ca-certificates           2019.6.16            hecc5488_0    conda-forge
certifi                   2019.6.16                py37_0    conda-forge
libblas                   3.8.0                7_openblas    conda-forge
libcblas                  3.8.0                7_openblas    conda-forge
libffi                    3.2.1             he1b5a44_1006    conda-forge
libgcc-ng                 9.1.0                hdf63c60_0    defaults
libgfortran-ng            7.3.0                hdf63c60_0    defaults
liblapack                 3.8.0                7_openblas    conda-forge
libstdcxx-ng              9.1.0                hdf63c60_0    defaults
ncurses                   6.1               hf484d3e_1002    conda-forge
numpy                     1.16.4           py37h95a1406_0    conda-forge
openblas                  0.3.5             h9ac9557_1001    conda-forge
openssl                   1.1.1b               h14c3975_1    conda-forge
pandas                    0.24.2           py37hb3f55d8_0    conda-forge
pip                       19.1.1                   py37_0    conda-forge
python                    3.7.3                h5b0a415_0    conda-forge
python-dateutil           2.8.0                      py_0    conda-forge
pytz                      2019.1                     py_0    conda-forge
readline                  7.0               hf8c457e_1001    conda-forge
setuptools                41.0.1                   py37_0    conda-forge
six                       1.12.0                py37_1000    conda-forge
sqlite                    3.28.0               h8b20d00_0    conda-forge
tk                        8.6.9             hed695b0_1002    conda-forge
wheel                     0.33.4                   py37_0    conda-forge
xz                        5.2.4             h14c3975_1001    conda-forge
zlib                      1.2.11            h14c3975_1004    conda-forge

```

**Comment by mjbeyeler** [comment]
@ocefpaf

**Comment by TomAugspurger** [comment]
You might try re-installing conda, or installing it in a different prefix,
on that other machine.

**Comment by ocefpaf** [comment]
> You might try re-installing conda, or installing it in a different prefix, on that other machine.

Also clean your package cache. You may have something corrupted there.

```
conda clean --all --yes -f
```

**Comment by mjbeyeler** [comment]
Sorry for the late response.

The problem turned out to be deeper. I don't understand what exactly it was, but it was somehow related to other python distributions that had previously been installed to the VM (not by conda).

In the end, I switched to a new VM, and now everything works fine.

So, you guys were right, the my machine was the problem. Thanks!
